#! /bin/sh
#chkconfig:  2345 81 96
#description: start jenkins

# path: /etc/init.d/jenkinsd
# description: process jenkins node service
# processname: jenkinsd

SERVICE_USER_NAME=SOFTWARE_USER_NAME
SERVICE_PROCESS_NAME=SOFTWARE_PROCESS_NAME
SERVICE_BIND_IP=SOFTWARE_BIND_IP
SERVICE_PORT=SOFTWARE_PORT
SERVICE_INSTALL_PATH=SOFTWARE_INSTALL_PATH
SERVICE_DATA_PATH=SOFTWARE_DATA_PATH
SERVICE_LOG_PATH=SOFTWARE_LOG_PATH

case "$1" in
    start)
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
        	echo "Starting service..."

            su - ${SERVICE_USER_NAME}  -c "java -DJENKINS_HOME=${SERVICE_DATA_PATH} -jar ${SERVICE_INSTALL_PATH}/jenkins.war --logfile=${SERVICE_LOG_PATH}/jenkins.log --webroot=${SERVICE_DATA_PATH}/war --daemon --httpListenAddress=${SERVICE_BIND_IP} --httpPort=${SERVICE_PORT}"

            sleep 2
            process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
            if [ -z "${process_id}" ];then
                echo "Start service error!"
                exit 1
            else
                echo "Start service success!"
            fi
		else
			echo "Service is running!"
        fi
    ;;
	stop)
		echo "Shutting down service..."
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
	        echo "There is no service running!"
     	else
            kill -9 ${process_id}
            echo "Service " ${process_id} " is killed!"
     	fi
        sleep 5
        echo "Service stop success!"
    ;;
	restart)
        $0 stop
        sleep 5
        $0 start
    ;;
	status)
		process_id=`ps -ef|grep -i "${SERVICE_PROCESS_NAME}" |grep -v "grep"|awk '{print $2}'`
		if [ -z "${process_id}" ];then
			echo "Service is not running!"
			exit 1
		else
			echo "Service is running!"
			exit 0
		fi
	;;
esac

